# Generated by Django 3.2.6 on 2022-06-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('client', models.CharField(max_length=50, null=True)),
                ('phoneNumber', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('carModel', models.CharField(max_length=50, null=True)),
                ('carNumber', models.CharField(max_length=50, null=True)),
                ('birth', models.CharField(max_length=50, null=True)),
                ('trim', models.CharField(max_length=50, null=True)),
                ('fuel1', models.CharField(max_length=50, null=True)),
                ('fuel2', models.CharField(max_length=50, null=True)),
                ('fuel3', models.CharField(max_length=50, null=True)),
                ('fuel4', models.CharField(max_length=50, null=True)),
                ('fuel5', models.CharField(max_length=50, null=True)),
                ('driveType1', models.CharField(max_length=50, null=True)),
                ('driveType2', models.CharField(max_length=50, null=True)),
                ('airBag', models.CharField(max_length=50, null=True)),
                ('mileage', models.CharField(max_length=50, null=True)),
                ('repairCost', models.CharField(max_length=50, null=True)),
                ('proposedCompensation', models.CharField(max_length=50, null=True)),
                ('insuranceCompany', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('others1', models.CharField(max_length=50, null=True)),
                ('others2', models.CharField(max_length=50, null=True)),
                ('others3', models.CharField(max_length=50, null=True)),
                ('note', models.CharField(max_length=500, null=True)),
                ('image1', models.ImageField(null=True, upload_to='posts')),
                ('image2', models.ImageField(null=True, upload_to='posts')),
                ('image3', models.ImageField(null=True, upload_to='posts')),
                ('image4', models.ImageField(null=True, upload_to='posts')),
                ('image5', models.ImageField(null=True, upload_to='posts')),
                ('image6', models.ImageField(null=True, upload_to='posts')),
            ],
        ),
    ]
