# Generated by Django 3.2.6 on 2022-06-22 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='airBag',
            new_name='airbag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='driveType1',
            new_name='driveType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='driveType2',
            new_name='eventDate',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fuel1',
            new_name='fuel',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fuel2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fuel3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fuel4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fuel5',
        ),
    ]
