# Generated by Django 3.2.6 on 2022-06-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220622_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventDate',
            field=models.DateTimeField(null=True),
        ),
    ]
