# Generated by Django 3.2.6 on 2022-06-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='eventDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
