# Generated by Django 3.2.6 on 2022-07-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image2',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image3',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image4',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image5',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image6',
            field=models.FileField(null=True, upload_to='posts'),
        ),
    ]
