# Generated by Django 3.2.6 on 2022-07-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220702_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image10',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image11',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image12',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image7',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image8',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image9',
            field=models.FileField(null=True, upload_to='posts'),
        ),
    ]
