# Generated by Django 3.2.6 on 2022-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20220702_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faultRatio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
