# Generated by Django 3.2.6 on 2022-07-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_faultratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='addition',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image13',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image14',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image15',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image16',
            field=models.FileField(null=True, upload_to='posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='image17',
            field=models.FileField(null=True, upload_to='posts'),
        ),
    ]
