# Generated by Django 3.2.6 on 2022-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='opinion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
