# Generated by Django 3.2.3 on 2022-07-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_opinion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='carNumber_masked',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
