# Generated by Django 3.2.6 on 2022-07-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_carnumber_masked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agreement',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
