# Generated by Django 3.2.3 on 2022-08-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
