# Generated by Django 3.2.6 on 2022-08-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_post_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='insuranceCompany_me',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
